import assert from 'node:assert/strict';
import { sixGraphsOf } from '../src/arch/sixGraphs';
import { analyzeDataFlow } from '../src/arch/dataflow';
const d=analyzeDataFlow('tatai');
assert(d.nodes.length && d.edges.length,'Real business declaration must be nonempty');
const byNode=sixGraphsOf('tatai',{mode:'full',graph:'data_flow',node_id:d.nodes[0].id}) as any;
assert.equal(byNode.node_focus.found,true);
assert.equal(byNode.node_focus.business_appearances[0].object.id,d.nodes[0].id);
assert.equal(byNode.node_focus.business_appearances[0].object.verification,d.nodes[0].verification);
assert.deepEqual(byNode.graphs.data_flow.primary_canvas,{layer:'business_data_flow',source:'tech',nodes:d.nodes.length,edges:d.edges.length,chains:d.chains.length});
const byEdge=sixGraphsOf('tatai',{mode:'full',graph:'data_flow',relation_id:d.edges[0].id}) as any;
assert.equal(byEdge.relation_focus.found,true);
assert.equal(byEdge.relation_focus.business_appearances[0].id,d.edges[0].id);
assert.equal(byEdge.relation_focus.business_appearances[0].verification,d.edges[0].verification);
const module=sixGraphsOf('tatai',{mode:'full',graph:'module_map'});
const real=module.graphs.module_map!.nodes.filter(n=>n.origin_layer==='code');
assert(real.length>0);
assert(real.every(n=>typeof n.path==='string' && n.path.length>0),'Code module paths available for drill-down');
const main=sixGraphsOf('tatai',{mode:'full',graph:'architecture'});
assert(Array.isArray(main.graphs.architecture!.unresolved_relations),'Full unresolved relation list is available');
const gap=main.graphs.architecture!.unresolved_relations![0];
assert(gap,'Real architecture unresolved relation is retained');
const byGap=sixGraphsOf('tatai',{mode:'full',graph:'architecture',relation_id:gap.id}) as any;
assert.equal(byGap.relation_focus.found,true);
assert.deepEqual(byGap.relation_focus.unresolved_appearances[0],{graph:'architecture',...gap});
assert.match(byGap.relation_focus.note,/关系存在但未绘为连线/,'Provenance must not obscure the unresolved relationship explanation');
console.log('PASS five-graph readout: business stable ID focus, original verification, primary canvas counts, module drill paths, unresolved relation list');
